### ISSUE TITLE
[Feature Req] More detailed dependency list

### ISSUE THREAD

**Issue by michael7198** [steven-murray/hmf#286]
**Is your feature request related to a problem? Please describe.**
Initializing a MassFunction() with `astropy=6.1.4` gives a `'FlatLambdaCDM' object has no attribute '_nu_info'` error, but works with 7.2.0 installed. The pip install log showed `Requirement already satisfied: astropy>=1.1`.

**Describe the solution you'd like**
A requirements.txt with necessary versions of the requisite packages. I haven't tested any other `astropy` version but >=7 may be what works. I'm not sure about the other packages.

This isn't an urgent request as I was able to easily update my astropy version, but it may be useful to others.
